defaults:
  - train_base

# data
dataset_type: moc_eg_wrong_one_way_nei
val_file: moc_eg_wrong_one_way_nei/val.tsv
test_file: moc_eg_wrong_one_way_nei/test.tsv

model_name: llava-hf/llava-v1.6-mistral-7b-hf
batch_size: 1
target_batch: 32
epochs: 5
project_name: llava
lr: 2e-5