# override
defaults:
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

# finetuning
target_run_id:

# output
run_dir:
cur_run_id:

# dataset
train_file:
val_file: moc/val.tsv
test_file: moc/test.tsv

# model
# openai/clip-vit-base-patch16
# openai/clip-vit-base-patch32
# openai/clip-vit-large-patch14
# openai/clip-vit-large-patch14-336

model_name: openai/clip-vit-base-patch32
class_num: 3

# training config
mode: train
num_workers: 4
batch_size: 256
target_batch: 2048
lr: 0.001
early_stop: 100
loss_weight_power: 2
epochs: 50
save_every_epoch: False
use_weight: False
reduction: sum

# misc
device:
seed: 42

# debug
debug: False

use_mask: True
project_name: random